# Generated by Django 3.2.7 on 2022-01-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_id', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=50)),
                ('createad_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email_address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('customer_shipping_address_id', models.CharField(blank=True, max_length=10, null=True)),
                ('customer_billing_address_id', models.CharField(blank=True, max_length=10, null=True)),
                ('organization_id', models.CharField(blank=True, max_length=10, null=True)),
                ('customer_type', models.CharField(blank=True, max_length=10, null=True)),
                ('createad_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.AutoField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=255)),
                ('createad_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_id', models.CharField(max_length=50)),
                ('state_code', models.CharField(max_length=50)),
                ('state_name', models.CharField(max_length=50)),
                ('createad_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('customer_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_line_1', models.TextField()),
                ('address_line_2', models.TextField()),
                ('country_id', models.CharField(max_length=50)),
                ('state_id', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('createad_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.customer')),
            ],
        ),
    ]
