# Generated by Django 3.2.11 on 2022-01-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstatus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
